---
title: "Riingo Fama French Tibbletime Shiny"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}

library(tidyquant)
library(tidyverse)
library(timetk)
library(broom)
library(tibbletime)
library(highcharter)
library(scales)
library(readr)
library(riingo)

knitr::opts_chunk$set(message=FALSE, warning=FALSE)

temp <- tempfile()

# enter your tiingo api key
riingo_set_token("97d26898fe27141ef524c1fa3ab0d3f0c3c59b09")

```


Sidebar {.sidebar}
====================================
  
```{r}

factor_choices <- c("Global 5 Factor Daily" = "Global_5_Factors_Daily",
                  "Japan 5 Factor Daily" = "Japan_5_Factors_Daily",
                  "Euro 5 Factor Daily" = "Europe_5_Factors_Daily",
                  "Global ex US 5 Factor Daily" = "Global_ex_US_5_Factors_Daily",
                  "Asia Ex Japan 5 Factor Daily" = "Asia_Pacific_ex_Japan_5_Factors_Daily",
                  "North America 5 Factor Daily" = "North_America_5_Factors_Daily")


selectInput("factor", 
            "FF Factor",
            choices = factor_choices,
            selected = "Global 5 Factor Daily")

fluidRow(
  column(6,
  textInput("stock1", "Stock 1", "SPY")),
  column(5,
  numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)  

fluidRow(
  column(6,
  textInput("stock2", "Stock 2", "EFA")),
  column(5,
  numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Stock 3", "IJS")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Stock 4", "EEM")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Stock 5", "AGG")),
  column(5,
  numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)

fluidRow(
  column(6,
  dateInput("date", "Starting Date", min = "2000-01-01", "2018-01-01", format = "yyyy-mm-dd")),
  column(5,
  numericInput("window", "Window", 100, min = 50, max = 250, step = 20))
)

actionButton("go", "Submit")
```

```{r}

prices_tiingo <- eventReactive(input$go, {
  
symbols <- c(input$stock1, input$stock2, 
             input$stock3, input$stock4, 
             input$stock5)

prices_tiingo <- 
  riingo_prices(symbols, start_date = input$date) %>% 
  select(ticker, date, adjClose)

returns_tiingo <- 
  prices_tiingo %>%
  group_by(ticker) %>%  
  mutate(returns = (log(adjClose) - log(lag(adjClose)))) 
  
w <- c(input$w1/100, input$w2/100, 
       input$w3/100, input$w4/100, input$w5/100)
  
portfolio_tiingo <-  
  returns_tiingo %>% 
  mutate(weights = case_when(
    ticker == symbols[1] ~ w[1],
    ticker == symbols[2] ~ w[2],
    ticker == symbols[3] ~ w[3],
    ticker == symbols[4] ~ w[4],
    ticker == symbols[5] ~ w[5]), 
  weighted_returns = returns * weights) %>% 
  group_by(date) %>% 
  summarise(returns = sum(weighted_returns))
})


```



```{r}

ff_portfolio_returns_joined <- eventReactive(input$go, {
  
portfolio_returns_daily <- prices_tiingo()

factors_address <- 
  paste("http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/", 
        input$factor, 
        "_CSV.zip", 
        sep="" )

download.file(factors_address, temp, quiet = TRUE)

factors_csv_name <- 
  paste(input$factor, ".csv", sep = "")
  
  FF_Factors <- 
  read_csv(unz(temp, factors_csv_name), skip = 6) %>% 
  rename(date = X1, MKT = `Mkt-RF`) %>%
  mutate(date = ymd(parse_date_time(date, "%Y%m%d"))) %>%
  mutate_if(is.character,as.numeric)
  
  ff_portfolio_returns <-
  portfolio_returns_daily %>%
  mutate(date = ymd(date)) %>% 
  left_join(FF_Factors %>%  mutate_if(is.numeric, funs(. / 100))) %>% 
  mutate(Returns_excess = returns - RF) %>%
  select(-returns, -RF) %>% 
  na.omit()
})

ff_dplyr_byhand <- eventReactive(input$go, {
  
  ff_portfolio_returns_joined() %>% 
  do(model = lm(Returns_excess ~ . -date , data = .)) 
  
})


rolling_ff <- eventReactive(input$go, {

# Create our rolling linear model using rollify.    
rolling_lm <- rollify(.f = function(Returns_excess, MKT, SMB, HML, RMW, CMA) {
                              lm(Returns_excess ~ MKT + SMB + HML + RMW + CMA)
                           }, 
                      window = input$window, 
                      unlist = FALSE)

rolling_ff <- 
  ff_portfolio_returns_joined() %>% 
  mutate(rolling_lm = rolling_lm(Returns_excess, MKT, SMB, HML, RMW, CMA)) %>% 
  slice(-1:-input$window)

})
```

```{r}
# Get rolling r squared as xts object
rolling_r_squared_xts <- eventReactive(input$go, {
  rolling_ff() %>% 
  mutate(glanced = map(rolling_lm, glance)) %>% 
  unnest(glanced) %>% 
  select(date, r.squared) %>% 
  tk_xts(date_var = date)
})
```

```{r}
# Get rolling factor betas as tibble
rolling_betas <- eventReactive(input$go, {
  
rolling_ff() %>%
  mutate(tidied = map(rolling_lm, tidy)) %>% 
  unnest(tidied) %>% 
  select(date, term, estimate) %>% 
  na.omit() %>%
  group_by(term) %>%
  filter(term != "(Intercept)")
})  
```

Fama French 
====================================

Row 1 {.tabset}
---------------------

### Rolling R Squared of 5-Factor Model

```{r}
renderHighchart({

highchart(type = "stock") %>% 
  hc_title(text = "Rolling R Squared") %>%
  hc_add_series(rolling_r_squared_xts(), color = "cornflowerblue") %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE)
})
```

Row 2 {.tabset}
------------------------------

### Rolling Betas for Each Factor

```{r}
renderPlot({
  rolling_betas() %>%  
  ggplot(aes(x = date, y = estimate, color = term)) + 
  geom_line()
})
```

### Model Results

```{r}
renderTable({
  ff_dplyr_byhand() %>% 
    glance(model) %>% 
    select(r.squared, adj.r.squared, sigma, statistic, p.value)
}, digits = 4)
```

### Factor Coefficients

```{r}
renderTable({
  ff_dplyr_byhand() %>% 
    tidy(model, conf.int = T)
}, digits = 4)
```

